[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000
<<<<<<< HEAD
listen.allowed_clients = any
=======
;listen.allowed_clients = 127.0.0.1
>>>>>>> branch-php-fpm

pm = dynamic
pm.max_children = 50
pm.start_servers = 15
pm.min_spare_servers = 10
pm.max_spare_servers = 25
pm.max_requests = 5000
request_terminate_timeout = 60

; Pass environment variables
clear_env = no

; Security
;catch_workers_output = yes
;decorate_workers_output = no

; Logs
access.log = /var/log/php-fpm/access.log
slowlog = /var/log/php-fpm/slow.log
request_slowlog_timeout = 5s
